### ISSUE TITLE
dbc loda_file error

### ISSUE THREAD

**Issue by ayongsir** [eerimoq/cantools#153]
Traceback (most recent call last):
  File "D:/MyProject/PyCharm/dbc/dbcReport.py", line 4, in <module>
    db = cantools.db.load_file('AC.dbc', database_format='dbc')
  File "D:\Anaconda3\envs\dbc\lib\site-packages\cantools\database\__init__.py", line 179, in load_file
    strict)
  File "D:\Anaconda3\envs\dbc\lib\site-packages\cantools\database\__init__.py", line 247, in load
    strict)
  File "D:\Anaconda3\envs\dbc\lib\site-packages\cantools\database\__init__.py", line 312, in load_string
    return load_can_database('dbc')
  File "D:\Anaconda3\envs\dbc\lib\site-packages\cantools\database\__init__.py", line 296, in load_can_database
    db.add_dbc_string(string)
  File "D:\Anaconda3\envs\dbc\lib\site-packages\cantools\database\can\database.py", line 165, in add_dbc_string
    database = dbc.load_string(string, self._strict)
  File "D:\Anaconda3\envs\dbc\lib\site-packages\cantools\database\can\formats\dbc.py", line 1386, in load_string
    attribute_definitions = get_definitions_dict(definitions, defaults)
  File "D:\Anaconda3\envs\dbc\lib\site-packages\cantools\database\can\formats\dbc.py", line 1362, in get_definitions_dict
    definition.minimum = convert_value(definition, values[0])
  File "D:\Anaconda3\envs\dbc\lib\site-packages\cantools\database\can\formats\dbc.py", line 1341, in convert_value
    value = int(value)
ValueError: invalid literal for int() with base 10: '-9.22337203685478E+018'

**Comment by geo4711** [comment]
do you still need help for this issue? Which version of cantools do you use? Could you upload the dbc where the error occurs?
