### ISSUE TITLE
KeyError: 515 in decode_message

### ISSUE THREAD

**Issue by robertosilviu** [eerimoq/cantools#206]
Hi, 
I'm trying to get the messages that i' m receiving on the can bus but when i try to decode the message i get this error:
`Traceback (most recent call last):
  File "can_send.py", line 16, in <module>
    data_received=db.decode_message(message.arbitration_id, message.data)
  File "/home/roberto/python_env/lib/python3.6/site-packages/cantools/database/can/database.py", line 387, in decode_message
    message = self._name_to_message[frame_id_or_name]
KeyError: 515`

It can be related to the dbc file i'm using? If i use a different one i don't have any problem. What i' m trying to do is:
```
db=cantools.db.load_file('file.dbc')
can_bus=can.interface.Bus(channel='vcan0', bustype='socketcan')
message=can_bus.recv()
data_received=db.decode_message(message.arbitration_id, message.data)
```
Thanks.

**Comment by robertosilviu** [comment]
I've managed to fix this issue by using directly the name and not frame_id. It decodes without problem when using the name.
