### ISSUE TITLE
Raspberry pi install fails?

### ISSUE THREAD

**Issue by jma1123** [eerimoq/cantools#270]
Any idea on the below error message for RPI installation failure?  Python-can installs successfully
Python3 installed
Latest Raspian image installed (1/2021)

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting cantools
  Using cached https://files.pythonhosted.org/packages/0c/36/8041395dfb10634bec3d85586d892f5f406bd661dc6ffc8e1e8fe8fae9e9/cantools-36.2.0.tar.gz
Collecting argparse_addons (from cantools)
  Using cached https://files.pythonhosted.org/packages/76/6d/a4342d968eeff3a5f35556a52a1310717558612fedbaa1c7e80626163ce4/argparse_addons-0.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-GwtrM_/argparse-addons/setup.py", line 4, in <module>
        import argparse_addons
      File "argparse_addons.py", line 19
        f'{string} is not in the range {self.minimum}..{self.maximum}')
                                                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-GwtrM_/argparse-addons/

**Comment by jma1123** [comment]
Never mind - sorry about that; pip vs. pip3 (duh) ;)
