### ISSUE TITLE
matplotlib package not installed after cantools installation

### ISSUE THREAD

**Issue by vkaser** [eerimoq/cantools#328]
OS: Ubuntu 20.04 LTS x86_64 
kernel: 5.8.0-59-generic

After `cantools` installation through `pip install ` the error appears when `cantools` run:
```
$ cantools 
matplotlib package not installed. Required for producing plots.
Traceback (most recent call last):
  File "/usr/local/bin/cantools", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.8/dist-packages/cantools/__init__.py", line 38, in _main
    from .subparsers import plot
  File "/usr/local/lib/python3.8/dist-packages/cantools/subparsers/plot.py", line 59, in <module>
    plt.rcParams["date.autoformatter.hour"] = "%H:%M"
NameError: name 'plt' is not defined
```

**Comment by ftab** [comment]
It's a little buried in the README:

>Note that by default matplotlib is not installed with cantools. But it can be by specifying an extra at installation:
>
>$ python3 -m pip install cantools[plot]

I think the first occurrence of the pip install in the readme should include matplotlib since it doesn't seem to run without it. Either that, or fix it to only require the matplotlib package if using the plot command.
